import { ThemeId } from '@/types/gift';

export interface ThemeTokens {
  id: ThemeId;
  name: string;
  tagline: string;
  colors: {
    background: string;
    surface: string;
    text: string;
    mutedText: string;
    accent: string;
    accentSecondary: string;
    glow: string;
    card: string;
    border: string;
    gradient: string;
  };
  particles: {
    type: 'hearts' | 'stars' | 'sakura' | 'leaves' | 'fireflies' | 'balloons' | 'confetti' | 'bubbles';
    primaryColor: string;
    secondaryColor: string;
    density: number;
  };
  cursor: {
    glowColor: string;
    trailEmoji: string;
  };
  typography: {
    headingFont: string;
    handwritingFont: string;
  };
  audio: {
    ambientPreset: string;
  };
  texture: 'aurora' | 'grain' | 'y2k_mesh' | 'paper' | 'toxic_glow' | 'cherry' | 'cloud' | 'emo_punk' | 'secret_dark';
}

const DEFAULT_TOKEN: ThemeTokens = {
  id: 'secret',
  name: 'SECRET 🕵️',
  tagline: 'Dark cinematic mystery, subtle film grain & confidential aura.',
  colors: {
    background: '#070709',
    surface: '#121217',
    text: '#F1F1F5',
    mutedText: '#94A3B8',
    accent: '#38BDF8',
    accentSecondary: '#6366F1',
    glow: '0 0 35px rgba(56, 189, 248, 0.4)',
    card: 'rgba(18, 18, 23, 0.85)',
    border: 'rgba(56, 189, 248, 0.3)',
    gradient: 'from-slate-950 via-zinc-950 to-neutral-950',
  },
  particles: { type: 'stars', primaryColor: '#38BDF8', secondaryColor: '#818CF8', density: 35 },
  cursor: { glowColor: '#38BDF8', trailEmoji: '🕵️' },
  typography: { headingFont: 'Clash Display', handwritingFont: 'Caveat' },
  audio: { ambientPreset: 'cosmic_synth' },
  texture: 'secret_dark',
};

export const THEME_REGISTRY: Record<ThemeId, ThemeTokens> = {
  secret: DEFAULT_TOKEN,
  crush: {
    id: 'crush',
    name: 'CRUSH 👀',
    tagline: 'Warm, intimate rose velvet, quiet longing & soft candlelight.',
    colors: {
      background: '#12070A',
      surface: '#210C12',
      text: '#FFF0F3',
      mutedText: '#FB7185',
      accent: '#FF4F9A',
      accentSecondary: '#FDA4AF',
      glow: '0 0 30px rgba(255, 79, 154, 0.5)',
      card: 'rgba(33, 12, 18, 0.85)',
      border: 'rgba(255, 79, 154, 0.35)',
      gradient: 'from-rose-950 via-pink-950 to-slate-950',
    },
    particles: { type: 'hearts', primaryColor: '#FF4F9A', secondaryColor: '#FDA4AF', density: 30 },
    cursor: { glowColor: '#FF4F9A', trailEmoji: '👀' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'harp_breeze' },
    texture: 'grain',
  },
  chaotic: {
    id: 'chaotic',
    name: 'CHAOTIC 💀',
    tagline: 'Messy screenshots, bold typography & unexpected interactions.',
    colors: {
      background: '#09090B',
      surface: '#18181B',
      text: '#FDE047',
      mutedText: '#F97316',
      accent: '#F59E0B',
      accentSecondary: '#EF4444',
      glow: '0 0 35px rgba(245, 158, 11, 0.7)',
      card: 'rgba(24, 24, 27, 0.85)',
      border: 'rgba(245, 158, 11, 0.5)',
      gradient: 'from-zinc-950 via-stone-900 to-amber-950',
    },
    particles: { type: 'fireflies', primaryColor: '#FACC15', secondaryColor: '#EF4444', density: 45 },
    cursor: { glowColor: '#F59E0B', trailEmoji: '💀' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'lofi_chaos' },
    texture: 'toxic_glow',
  },
  romantic: {
    id: 'romantic',
    name: 'ROMANTIC ❤️',
    tagline: 'Elegant A24 cinematic romance, velvet glass & deep feelings.',
    colors: {
      background: '#140509',
      surface: '#240A12',
      text: '#FFE4E6',
      mutedText: '#FB7185',
      accent: '#F43F5E',
      accentSecondary: '#FDA4AF',
      glow: '0 0 30px rgba(244, 63, 94, 0.5)',
      card: 'rgba(36, 10, 18, 0.8)',
      border: 'rgba(244, 63, 94, 0.4)',
      gradient: 'from-rose-950 via-red-950 to-pink-950',
    },
    particles: { type: 'hearts', primaryColor: '#FB7185', secondaryColor: '#FDA4AF', density: 35 },
    cursor: { glowColor: '#F43F5E', trailEmoji: '❤️' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'harp_breeze' },
    texture: 'cherry',
  },
  nostalgia: {
    id: 'nostalgia',
    name: 'NOSTALGIA 🥀',
    tagline: 'Sepia film grain, polaroid memories & bittersweet soft transitions.',
    colors: {
      background: '#171311',
      surface: '#261F1C',
      text: '#FEF3C7',
      mutedText: '#D97706',
      accent: '#F59E0B',
      accentSecondary: '#B45309',
      glow: '0 0 25px rgba(245, 158, 11, 0.4)',
      card: 'rgba(38, 31, 28, 0.85)',
      border: 'rgba(245, 158, 11, 0.35)',
      gradient: 'from-stone-950 via-amber-950 to-zinc-950',
    },
    particles: { type: 'confetti', primaryColor: '#F59E0B', secondaryColor: '#B45309', density: 25 },
    cursor: { glowColor: '#F59E0B', trailEmoji: '🥀' },
    typography: { headingFont: 'General Sans', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'vinyl_crackle' },
    texture: 'paper',
  },
  delulu: {
    id: 'delulu',
    name: 'DELULU 🫠',
    tagline: 'Dreamlike magenta, surreal butterflies & unapologetic hope.',
    colors: {
      background: '#1A0B1A',
      surface: '#2D122D',
      text: '#FCE7F3',
      mutedText: '#F472B6',
      accent: '#EC4899',
      accentSecondary: '#E879F9',
      glow: '0 0 30px rgba(236, 72, 153, 0.5)',
      card: 'rgba(45, 18, 45, 0.8)',
      border: 'rgba(236, 72, 153, 0.4)',
      gradient: 'from-pink-950 via-purple-950 to-fuchsia-950',
    },
    particles: { type: 'sakura', primaryColor: '#F472B6', secondaryColor: '#E879F9', density: 40 },
    cursor: { glowColor: '#EC4899', trailEmoji: '🦋' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'synthwave_pulse' },
    texture: 'y2k_mesh',
  },
  main_character: {
    id: 'main_character',
    name: 'MAIN CHARACTER ✨',
    tagline: 'High-energy golden aura, spotlight shimmer & main character vibes.',
    colors: {
      background: '#0C0A09',
      surface: '#1C1917',
      text: '#FEF08A',
      mutedText: '#EAB308',
      accent: '#EAB308',
      accentSecondary: '#FACC15',
      glow: '0 0 35px rgba(234, 179, 8, 0.6)',
      card: 'rgba(28, 25, 23, 0.85)',
      border: 'rgba(234, 179, 8, 0.5)',
      gradient: 'from-amber-950 via-purple-950 to-stone-950',
    },
    particles: { type: 'stars', primaryColor: '#FACC15', secondaryColor: '#FEF08A', density: 40 },
    cursor: { glowColor: '#EAB308', trailEmoji: '👑' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'grand_orchestral' },
    texture: 'aurora',
  },
  bro_code: {
    id: 'bro_code',
    name: 'BRO CODE 🗿',
    tagline: 'Dark obsidian, bold typography, funny memes & bro energy.',
    colors: {
      background: '#0F172A',
      surface: '#1E293B',
      text: '#F1F5F9',
      mutedText: '#94A3B8',
      accent: '#38BDF8',
      accentSecondary: '#0284C7',
      glow: '0 0 25px rgba(56, 189, 248, 0.5)',
      card: 'rgba(30, 41, 59, 0.85)',
      border: 'rgba(56, 189, 248, 0.4)',
      gradient: 'from-slate-950 via-zinc-900 to-stone-950',
    },
    particles: { type: 'confetti', primaryColor: '#38BDF8', secondaryColor: '#F59E0B', density: 30 },
    cursor: { glowColor: '#38BDF8', trailEmoji: '🗿' },
    typography: { headingFont: 'General Sans', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'vinyl_crackle' },
    texture: 'grain',
  },
  midnight: {
    id: 'midnight',
    name: 'MIDNIGHT 🌌',
    tagline: 'Dark cinematic atmosphere, glowing stars & neon pulses.',
    colors: {
      background: '#08090D',
      surface: '#11131F',
      text: '#F5F3FF',
      mutedText: '#A78BFA',
      accent: '#8B5CF6',
      accentSecondary: '#C084FC',
      glow: '0 0 35px rgba(139, 92, 246, 0.6)',
      card: 'rgba(17, 19, 31, 0.75)',
      border: 'rgba(139, 92, 246, 0.4)',
      gradient: 'from-slate-950 via-purple-950 to-slate-900',
    },
    particles: { type: 'stars', primaryColor: '#E9D5FF', secondaryColor: '#38BDF8', density: 45 },
    cursor: { glowColor: '#8B5CF6', trailEmoji: '✨' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'cosmic_synth' },
    texture: 'aurora',
  },
  pink_crush: {
    id: 'pink_crush',
    name: 'PINK CRUSH 🩷',
    tagline: 'Romantic blush pink, deep rose velvet & sweet affection.',
    colors: {
      background: '#FFF0F6',
      surface: '#FFE3EE',
      text: '#24121D',
      mutedText: '#992B60',
      accent: '#FF4F9A',
      accentSecondary: '#E60067',
      glow: '0 0 30px rgba(255, 79, 154, 0.4)',
      card: 'rgba(255, 255, 255, 0.85)',
      border: 'rgba(255, 79, 154, 0.35)',
      gradient: 'from-pink-100 via-rose-100 to-purple-100',
    },
    particles: { type: 'hearts', primaryColor: '#FF4F9A', secondaryColor: '#F472B6', density: 35 },
    cursor: { glowColor: '#FF4F9A', trailEmoji: '🩷' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'harp_breeze' },
    texture: 'grain',
  },
  y2k: {
    id: 'y2k',
    name: 'Y2K 🦋',
    tagline: 'Internet 2000s cyber cyan, mesh gradient & butterfly magic.',
    colors: {
      background: '#DFFFFB',
      surface: '#C4F6EE',
      text: '#111827',
      mutedText: '#0891B2',
      accent: '#00D4FF',
      accentSecondary: '#06B6D4',
      glow: '0 0 35px rgba(0, 212, 255, 0.5)',
      card: 'rgba(255, 255, 255, 0.8)',
      border: 'rgba(0, 212, 255, 0.4)',
      gradient: 'from-cyan-100 via-teal-100 to-sky-100',
    },
    particles: { type: 'bubbles', primaryColor: '#00D4FF', secondaryColor: '#38BDF8', density: 35 },
    cursor: { glowColor: '#00D4FF', trailEmoji: '🦋' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'synthwave_pulse' },
    texture: 'y2k_mesh',
  },
  cherry_bomb: {
    id: 'cherry_bomb',
    name: 'CHERRY BOMB 🍒',
    tagline: 'Bold dark cherry, fiery crimson glow & high passion.',
    colors: {
      background: '#17070B',
      surface: '#290D13',
      text: '#FFF1F2',
      mutedText: '#FB7185',
      accent: '#FF3158',
      accentSecondary: '#E11D48',
      glow: '0 0 35px rgba(255, 49, 88, 0.6)',
      card: 'rgba(41, 13, 19, 0.8)',
      border: 'rgba(255, 49, 88, 0.4)',
      gradient: 'from-rose-950 via-red-950 to-slate-950',
    },
    particles: { type: 'fireflies', primaryColor: '#FF3158', secondaryColor: '#FB7185', density: 40 },
    cursor: { glowColor: '#FF3158', trailEmoji: '🍒' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'lofi_piano' },
    texture: 'cherry',
  },
  juicebox: {
    id: 'juicebox',
    name: 'JUICEBOX 🧃',
    tagline: 'Playful warm orange, cheerful pop & sunny energy.',
    colors: {
      background: '#FFF7C7',
      surface: '#FFEE99',
      text: '#191919',
      mutedText: '#C2410C',
      accent: '#FF7A00',
      accentSecondary: '#F59E0B',
      glow: '0 0 25px rgba(255, 122, 0, 0.4)',
      card: 'rgba(255, 255, 255, 0.85)',
      border: 'rgba(255, 122, 0, 0.35)',
      gradient: 'from-amber-100 via-orange-100 to-yellow-100',
    },
    particles: { type: 'confetti', primaryColor: '#FF7A00', secondaryColor: '#F59E0B', density: 30 },
    cursor: { glowColor: '#FF7A00', trailEmoji: '🧃' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'sweet_musicbox' },
    texture: 'grain',
  },
  cloudcore: {
    id: 'cloudcore',
    name: 'CLOUDCORE 🫧',
    tagline: 'Soft sky blue, dreamy pastel clouds & calm serenity.',
    colors: {
      background: '#EAF6FF',
      surface: '#D6EDFF',
      text: '#172033',
      mutedText: '#0284C7',
      accent: '#7DD3FC',
      accentSecondary: '#38BDF8',
      glow: '0 0 25px rgba(125, 211, 252, 0.5)',
      card: 'rgba(255, 255, 255, 0.85)',
      border: 'rgba(125, 211, 252, 0.4)',
      gradient: 'from-sky-100 via-indigo-50 to-blue-100',
    },
    particles: { type: 'bubbles', primaryColor: '#7DD3FC', secondaryColor: '#BAE6FD', density: 25 },
    cursor: { glowColor: '#7DD3FC', trailEmoji: '🫧' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'lofi_piano' },
    texture: 'cloud',
  },
  toxic_bestie: {
    id: 'toxic_bestie',
    name: 'TOXIC BESTIE 💚',
    tagline: 'Chaotic electric neon lime, brat aesthetic & unhinged energy.',
    colors: {
      background: '#E9FFD8',
      surface: '#D2FFA6',
      text: '#101810',
      mutedText: '#4D7C0F',
      accent: '#72FF00',
      accentSecondary: '#84CC16',
      glow: '0 0 35px rgba(114, 255, 0, 0.6)',
      card: 'rgba(255, 255, 255, 0.85)',
      border: 'rgba(114, 255, 0, 0.5)',
      gradient: 'from-lime-100 via-emerald-100 to-green-100',
    },
    particles: { type: 'fireflies', primaryColor: '#72FF00', secondaryColor: '#A3E635', density: 45 },
    cursor: { glowColor: '#72FF00', trailEmoji: '💀' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'synthwave_pulse' },
    texture: 'toxic_glow',
  },
  emo: {
    id: 'emo',
    name: 'EMO 🖤',
    tagline: 'Edgy obsidian black, hot pink punk glow & raw feelings.',
    colors: {
      background: '#090909',
      surface: '#171717',
      text: '#E5E5E5',
      mutedText: '#F43F5E',
      accent: '#FF3B81',
      accentSecondary: '#E11D48',
      glow: '0 0 35px rgba(255, 59, 129, 0.6)',
      card: 'rgba(23, 23, 23, 0.85)',
      border: 'rgba(255, 59, 129, 0.4)',
      gradient: 'from-neutral-950 via-zinc-900 to-stone-950',
    },
    particles: { type: 'hearts', primaryColor: '#FF3B81', secondaryColor: '#F43F5E', density: 35 },
    cursor: { glowColor: '#FF3B81', trailEmoji: '🖤' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'vinyl_crackle' },
    texture: 'emo_punk',
  },
  scrapbook: {
    id: 'scrapbook',
    name: 'SCRAPBOOK 📜',
    tagline: 'Polaroid frames, paper grain textures & vintage notes.',
    colors: {
      background: '#FFFBEB',
      surface: '#FEF3C7',
      text: '#78350F',
      mutedText: '#D97706',
      accent: '#F59E0B',
      accentSecondary: '#B45309',
      glow: '0 0 20px rgba(245, 158, 11, 0.4)',
      card: 'rgba(255, 251, 235, 0.95)',
      border: 'rgba(245, 158, 11, 0.4)',
      gradient: 'from-orange-100 via-amber-100 to-rose-100',
    },
    particles: { type: 'hearts', primaryColor: '#F59E0B', secondaryColor: '#F472B6', density: 30 },
    cursor: { glowColor: '#F59E0B', trailEmoji: '📜' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'paper_rustle' },
    texture: 'paper',
  },
  soft: {
    id: 'soft',
    name: 'SOFT ☁️',
    tagline: 'Warm pastels, serene gradient clouds & sweet elegance.',
    colors: {
      background: '#FFF0F5',
      surface: '#FCE7F3',
      text: '#881337',
      mutedText: '#E11D48',
      accent: '#F472B6',
      accentSecondary: '#C084FC',
      glow: '0 0 20px rgba(244, 114, 182, 0.4)',
      card: 'rgba(255, 255, 255, 0.85)',
      border: 'rgba(244, 114, 182, 0.35)',
      gradient: 'from-rose-100 via-purple-50 to-sky-100',
    },
    particles: { type: 'bubbles', primaryColor: '#F472B6', secondaryColor: '#C084FC', density: 25 },
    cursor: { glowColor: '#F472B6', trailEmoji: '☁️' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'lofi_piano' },
    texture: 'cloud',
  },
  galaxy: DEFAULT_TOKEN,
  anime: DEFAULT_TOKEN,
  cute: DEFAULT_TOKEN,
  minimal: DEFAULT_TOKEN,
  luxury: DEFAULT_TOKEN,
  nature: DEFAULT_TOKEN,
  flowers: DEFAULT_TOKEN,
  retro: DEFAULT_TOKEN,
  neon: DEFAULT_TOKEN,
};
