import { ThemeId } from '@/types/gift';

export interface ThemeTokens {
  id: ThemeId;
  name: string;
  tagline: string;
  colors: {
    background: string;       // Primary background hex/gradient
    surface: string;          // Card surface
    text: string;             // Primary text color
    mutedText: string;        // Secondary/muted text color
    accent: string;           // Primary accent color
    accentSecondary: string;  // Secondary accent color
    glow: string;             // Glow box-shadow / aura
    card: string;             // Card backdrop rgba
    border: string;           // Border rgba
    gradient: string;         // Tailwind bg-gradient string
  };
  particles: {
    type: 'hearts' | 'stars' | 'sakura' | 'leaves' | 'fireflies' | 'balloons' | 'confetti' | 'bubbles';
    primaryColor: string;
    secondaryColor: string;
    density: number;
  };
  cursor: {
    glowColor: string;
    trailEmoji: string;
  };
  typography: {
    headingFont: string;
    handwritingFont: string;
  };
  audio: {
    ambientPreset: string;
  };
  texture: 'aurora' | 'grain' | 'y2k_mesh' | 'paper' | 'toxic_glow' | 'cherry' | 'cloud' | 'emo_punk';
}

export const THEME_REGISTRY: Record<ThemeId, ThemeTokens> = {
  midnight: {
    id: 'midnight',
    name: 'MIDNIGHT 🌌',
    tagline: 'Dark cinematic atmosphere, glowing stars & neon pulses.',
    colors: {
      background: '#08090D',
      surface: '#11131F',
      text: '#F5F3FF',
      mutedText: '#A78BFA',
      accent: '#8B5CF6',
      accentSecondary: '#C084FC',
      glow: '0 0 35px rgba(139, 92, 246, 0.6)',
      card: 'rgba(17, 19, 31, 0.75)',
      border: 'rgba(139, 92, 246, 0.4)',
      gradient: 'from-slate-950 via-purple-950 to-slate-900',
    },
    particles: { type: 'stars', primaryColor: '#E9D5FF', secondaryColor: '#38BDF8', density: 45 },
    cursor: { glowColor: '#8B5CF6', trailEmoji: '✨' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'cosmic_synth' },
    texture: 'aurora',
  },
  pink_crush: {
    id: 'pink_crush',
    name: 'PINK CRUSH 🩷',
    tagline: 'Romantic blush pink, deep rose velvet & sweet affection.',
    colors: {
      background: '#FFF0F6',
      surface: '#FFE3EE',
      text: '#24121D',
      mutedText: '#992B60',
      accent: '#FF4F9A',
      accentSecondary: '#E60067',
      glow: '0 0 30px rgba(255, 79, 154, 0.4)',
      card: 'rgba(255, 255, 255, 0.85)',
      border: 'rgba(255, 79, 154, 0.35)',
      gradient: 'from-pink-100 via-rose-100 to-purple-100',
    },
    particles: { type: 'hearts', primaryColor: '#FF4F9A', secondaryColor: '#F472B6', density: 35 },
    cursor: { glowColor: '#FF4F9A', trailEmoji: '🩷' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'harp_breeze' },
    texture: 'grain',
  },
  y2k: {
    id: 'y2k',
    name: 'Y2K 🦋',
    tagline: 'Internet 2000s cyber cyan, mesh gradient & butterfly magic.',
    colors: {
      background: '#DFFFFB',
      surface: '#C4F6EE',
      text: '#111827',
      mutedText: '#0891B2',
      accent: '#00D4FF',
      accentSecondary: '#06B6D4',
      glow: '0 0 35px rgba(0, 212, 255, 0.5)',
      card: 'rgba(255, 255, 255, 0.8)',
      border: 'rgba(0, 212, 255, 0.4)',
      gradient: 'from-cyan-100 via-teal-100 to-sky-100',
    },
    particles: { type: 'bubbles', primaryColor: '#00D4FF', secondaryColor: '#38BDF8', density: 35 },
    cursor: { glowColor: '#00D4FF', trailEmoji: '🦋' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'synthwave_pulse' },
    texture: 'y2k_mesh',
  },
  cherry_bomb: {
    id: 'cherry_bomb',
    name: 'CHERRY BOMB 🍒',
    tagline: 'Bold dark cherry, fiery crimson glow & high passion.',
    colors: {
      background: '#17070B',
      surface: '#290D13',
      text: '#FFF1F2',
      mutedText: '#FB7185',
      accent: '#FF3158',
      accentSecondary: '#E11D48',
      glow: '0 0 35px rgba(255, 49, 88, 0.6)',
      card: 'rgba(41, 13, 19, 0.8)',
      border: 'rgba(255, 49, 88, 0.4)',
      gradient: 'from-rose-950 via-red-950 to-slate-950',
    },
    particles: { type: 'fireflies', primaryColor: '#FF3158', secondaryColor: '#FB7185', density: 40 },
    cursor: { glowColor: '#FF3158', trailEmoji: '🍒' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'lofi_piano' },
    texture: 'cherry',
  },
  juicebox: {
    id: 'juicebox',
    name: 'JUICEBOX 🧃',
    tagline: 'Playful warm orange, cheerful pop & sunny energy.',
    colors: {
      background: '#FFF7C7',
      surface: '#FFEE99',
      text: '#191919',
      mutedText: '#C2410C',
      accent: '#FF7A00',
      accentSecondary: '#F59E0B',
      glow: '0 0 25px rgba(255, 122, 0, 0.4)',
      card: 'rgba(255, 255, 255, 0.85)',
      border: 'rgba(255, 122, 0, 0.35)',
      gradient: 'from-amber-100 via-orange-100 to-yellow-100',
    },
    particles: { type: 'confetti', primaryColor: '#FF7A00', secondaryColor: '#F59E0B', density: 30 },
    cursor: { glowColor: '#FF7A00', trailEmoji: '🧃' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'sweet_musicbox' },
    texture: 'grain',
  },
  cloudcore: {
    id: 'cloudcore',
    name: 'CLOUDCORE 🫧',
    tagline: 'Soft sky blue, dreamy pastel clouds & calm serenity.',
    colors: {
      background: '#EAF6FF',
      surface: '#D6EDFF',
      text: '#172033',
      mutedText: '#0284C7',
      accent: '#7DD3FC',
      accentSecondary: '#38BDF8',
      glow: '0 0 25px rgba(125, 211, 252, 0.5)',
      card: 'rgba(255, 255, 255, 0.85)',
      border: 'rgba(125, 211, 252, 0.4)',
      gradient: 'from-sky-100 via-indigo-50 to-blue-100',
    },
    particles: { type: 'bubbles', primaryColor: '#7DD3FC', secondaryColor: '#BAE6FD', density: 25 },
    cursor: { glowColor: '#7DD3FC', trailEmoji: '🫧' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'lofi_piano' },
    texture: 'cloud',
  },
  toxic_bestie: {
    id: 'toxic_bestie',
    name: 'TOXIC BESTIE 💚',
    tagline: 'Chaotic electric neon lime, brat aesthetic & unhinged energy.',
    colors: {
      background: '#E9FFD8',
      surface: '#D2FFA6',
      text: '#101810',
      mutedText: '#4D7C0F',
      accent: '#72FF00',
      accentSecondary: '#84CC16',
      glow: '0 0 35px rgba(114, 255, 0, 0.6)',
      card: 'rgba(255, 255, 255, 0.85)',
      border: 'rgba(114, 255, 0, 0.5)',
      gradient: 'from-lime-100 via-emerald-100 to-green-100',
    },
    particles: { type: 'fireflies', primaryColor: '#72FF00', secondaryColor: '#A3E635', density: 45 },
    cursor: { glowColor: '#72FF00', trailEmoji: '💀' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'synthwave_pulse' },
    texture: 'toxic_glow',
  },
  emo: {
    id: 'emo',
    name: 'EMO 🖤',
    tagline: 'Edgy obsidian black, hot pink punk glow & raw feelings.',
    colors: {
      background: '#090909',
      surface: '#171717',
      text: '#E5E5E5',
      mutedText: '#F43F5E',
      accent: '#FF3B81',
      accentSecondary: '#E11D48',
      glow: '0 0 35px rgba(255, 59, 129, 0.6)',
      card: 'rgba(23, 23, 23, 0.85)',
      border: 'rgba(255, 59, 129, 0.4)',
      gradient: 'from-neutral-950 via-zinc-900 to-stone-950',
    },
    particles: { type: 'hearts', primaryColor: '#FF3B81', secondaryColor: '#F43F5E', density: 35 },
    cursor: { glowColor: '#FF3B81', trailEmoji: '🖤' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'vinyl_crackle' },
    texture: 'emo_punk',
  },
  scrapbook: {
    id: 'scrapbook',
    name: 'SCRAPBOOK 📜',
    tagline: 'Polaroid frames, paper grain textures, washi tape & stamps.',
    colors: {
      background: '#FFFBEB',
      surface: '#FEF3C7',
      text: '#78350F',
      mutedText: '#D97706',
      accent: '#F59E0B',
      accentSecondary: '#B45309',
      glow: '0 0 20px rgba(245, 158, 11, 0.4)',
      card: 'rgba(255, 251, 235, 0.95)',
      border: 'rgba(245, 158, 11, 0.4)',
      gradient: 'from-orange-100 via-amber-100 to-rose-100',
    },
    particles: { type: 'hearts', primaryColor: '#F59E0B', secondaryColor: '#F472B6', density: 30 },
    cursor: { glowColor: '#F59E0B', trailEmoji: '🎀' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'paper_rustle' },
    texture: 'paper',
  },
  chaotic: {
    id: 'chaotic',
    name: 'CHAOTIC 💀',
    tagline: 'Unhinged memes, vibrant neon contrasts & pure energy.',
    colors: {
      background: '#09090B',
      surface: '#18181B',
      text: '#FDE047',
      mutedText: '#F97316',
      accent: '#F59E0B',
      accentSecondary: '#EF4444',
      glow: '0 0 35px rgba(245, 158, 11, 0.7)',
      card: 'rgba(24, 24, 27, 0.85)',
      border: 'rgba(245, 158, 11, 0.5)',
      gradient: 'from-zinc-950 via-stone-900 to-amber-950',
    },
    particles: { type: 'fireflies', primaryColor: '#FACC15', secondaryColor: '#EF4444', density: 45 },
    cursor: { glowColor: '#F59E0B', trailEmoji: '💀' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'lofi_chaos' },
    texture: 'toxic_glow',
  },
  soft: {
    id: 'soft',
    name: 'SOFT ☁️',
    tagline: 'Warm pastels, serene gradient clouds & sweet elegance.',
    colors: {
      background: '#FFF0F5',
      surface: '#FCE7F3',
      text: '#881337',
      mutedText: '#E11D48',
      accent: '#F472B6',
      accentSecondary: '#C084FC',
      glow: '0 0 20px rgba(244, 114, 182, 0.4)',
      card: 'rgba(255, 255, 255, 0.85)',
      border: 'rgba(244, 114, 182, 0.35)',
      gradient: 'from-rose-100 via-purple-50 to-sky-100',
    },
    particles: { type: 'bubbles', primaryColor: '#F472B6', secondaryColor: '#C084FC', density: 25 },
    cursor: { glowColor: '#F472B6', trailEmoji: '☁️' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'lofi_piano' },
    texture: 'cloud',
  },
  main_character: {
    id: 'main_character',
    name: 'MAIN CHARACTER ✨',
    tagline: 'High-energy golden aura, spotlight shimmer & main character vibes.',
    colors: {
      background: '#0C0A09',
      surface: '#1C1917',
      text: '#FEF08A',
      mutedText: '#EAB308',
      accent: '#EAB308',
      accentSecondary: '#FACC15',
      glow: '0 0 35px rgba(234, 179, 8, 0.6)',
      card: 'rgba(28, 25, 23, 0.85)',
      border: 'rgba(234, 179, 8, 0.5)',
      gradient: 'from-amber-950 via-purple-950 to-stone-950',
    },
    particles: { type: 'stars', primaryColor: '#FACC15', secondaryColor: '#FEF08A', density: 40 },
    cursor: { glowColor: '#EAB308', trailEmoji: '👑' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'grand_orchestral' },
    texture: 'aurora',
  },
  romantic: {
    id: 'romantic',
    name: 'ROMANTIC ❤️',
    tagline: 'Intimate deep rose velvet, floating hearts & candlelight warmth.',
    colors: {
      background: '#140509',
      surface: '#240A12',
      text: '#FFE4E6',
      mutedText: '#FB7185',
      accent: '#F43F5E',
      accentSecondary: '#FDA4AF',
      glow: '0 0 30px rgba(244, 63, 94, 0.5)',
      card: 'rgba(36, 10, 18, 0.8)',
      border: 'rgba(244, 63, 94, 0.4)',
      gradient: 'from-rose-950 via-red-950 to-pink-950',
    },
    particles: { type: 'hearts', primaryColor: '#FB7185', secondaryColor: '#FDA4AF', density: 35 },
    cursor: { glowColor: '#F43F5E', trailEmoji: '❤️' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'harp_breeze' },
    texture: 'cherry',
  },
  bro_code: {
    id: 'bro_code',
    name: 'BRO CODE 🗿',
    tagline: 'Dark obsidian, bold typography, funny memes & bro energy.',
    colors: {
      background: '#0F172A',
      surface: '#1E293B',
      text: '#F1F5F9',
      mutedText: '#94A3B8',
      accent: '#38BDF8',
      accentSecondary: '#0284C7',
      glow: '0 0 25px rgba(56, 189, 248, 0.5)',
      card: 'rgba(30, 41, 59, 0.85)',
      border: 'rgba(56, 189, 248, 0.4)',
      gradient: 'from-slate-950 via-zinc-900 to-stone-950',
    },
    particles: { type: 'confetti', primaryColor: '#38BDF8', secondaryColor: '#F59E0B', density: 30 },
    cursor: { glowColor: '#38BDF8', trailEmoji: '🗿' },
    typography: { headingFont: 'General Sans', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'vinyl_crackle' },
    texture: 'grain',
  },
  delulu: {
    id: 'delulu',
    name: 'DELULU 🥀',
    tagline: 'Dreamy magenta, butterfly magic & unapologetic romance.',
    colors: {
      background: '#1A0B1A',
      surface: '#2D122D',
      text: '#FCE7F3',
      mutedText: '#F472B6',
      accent: '#EC4899',
      accentSecondary: '#E879F9',
      glow: '0 0 30px rgba(236, 72, 153, 0.5)',
      card: 'rgba(45, 18, 45, 0.8)',
      border: 'rgba(236, 72, 153, 0.4)',
      gradient: 'from-pink-950 via-purple-950 to-fuchsia-950',
    },
    particles: { type: 'sakura', primaryColor: '#F472B6', secondaryColor: '#E879F9', density: 40 },
    cursor: { glowColor: '#EC4899', trailEmoji: '🦋' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'synthwave_pulse' },
    texture: 'y2k_mesh',
  },
  galaxy: {
    id: 'galaxy',
    name: 'Galaxy Dreams',
    tagline: 'Infinite cosmic dust and twinkling constellations.',
    colors: {
      background: '#08090D',
      surface: '#11131F',
      text: '#F3E8FF',
      mutedText: '#C084FC',
      accent: '#C084FC',
      accentSecondary: '#38BDF8',
      glow: '0 0 25px rgba(192, 132, 252, 0.5)',
      card: 'rgba(23, 15, 38, 0.65)',
      border: 'rgba(168, 85, 247, 0.3)',
      gradient: 'from-slate-950 via-purple-950 to-slate-900',
    },
    particles: { type: 'stars', primaryColor: '#E9D5FF', secondaryColor: '#38BDF8', density: 45 },
    cursor: { glowColor: '#C084FC', trailEmoji: '✨' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'cosmic_synth' },
    texture: 'aurora',
  },
  anime: {
    id: 'anime',
    name: 'Sakura Anime',
    tagline: 'Falling cherry blossoms and soft pastel dreams.',
    colors: {
      background: '#FFF0F5',
      surface: '#FCE7F3',
      text: '#881337',
      mutedText: '#E11D48',
      accent: '#EC4899',
      accentSecondary: '#FB7185',
      glow: '0 0 20px rgba(236, 72, 153, 0.4)',
      card: 'rgba(255, 255, 255, 0.75)',
      border: 'rgba(244, 114, 182, 0.4)',
      gradient: 'from-pink-100 via-purple-100 to-rose-200',
    },
    particles: { type: 'sakura', primaryColor: '#F472B6', secondaryColor: '#FB7185', density: 35 },
    cursor: { glowColor: '#F472B6', trailEmoji: '🌸' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'lofi_piano' },
    texture: 'grain',
  },
  cute: {
    id: 'cute',
    name: 'Cute Blobs & Hearts',
    tagline: 'Soft pastels, floating clouds, and sweet micro-interactions.',
    colors: {
      background: '#FFF0F5',
      surface: '#FCE7F3',
      text: '#4C1D95',
      mutedText: '#7C3AED',
      accent: '#FB7185',
      accentSecondary: '#C084FC',
      glow: '0 0 20px rgba(251, 113, 133, 0.4)',
      card: 'rgba(255, 255, 255, 0.8)',
      border: 'rgba(251, 113, 133, 0.35)',
      gradient: 'from-rose-100 via-amber-100 to-sky-100',
    },
    particles: { type: 'hearts', primaryColor: '#FDA4AF', secondaryColor: '#C084FC', density: 30 },
    cursor: { glowColor: '#FDA4AF', trailEmoji: '❤️' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'sweet_musicbox' },
    texture: 'cloud',
  },
  minimal: {
    id: 'minimal',
    name: 'Sleek Warm Minimal',
    tagline: 'Clean typography, subtle shadows, and effortless elegance.',
    colors: {
      background: '#FAFAF9',
      surface: '#F5F5F4',
      text: '#1C1917',
      mutedText: '#78716C',
      accent: '#D97706',
      accentSecondary: '#F59E0B',
      glow: '0 0 15px rgba(217, 119, 6, 0.3)',
      card: 'rgba(255, 255, 255, 0.9)',
      border: 'rgba(214, 211, 209, 0.6)',
      gradient: 'from-amber-50 via-stone-100 to-orange-50',
    },
    particles: { type: 'bubbles', primaryColor: '#F59E0B', secondaryColor: '#D97706', density: 20 },
    cursor: { glowColor: '#F59E0B', trailEmoji: '✨' },
    typography: { headingFont: 'General Sans', handwritingFont: 'Satisfy' },
    audio: { ambientPreset: 'minimal_acoustic' },
    texture: 'grain',
  },
  luxury: {
    id: 'luxury',
    name: 'Obsidian & Gold',
    tagline: 'Dark champagne luxury, velvet glass, and golden sparkle.',
    colors: {
      background: '#09090B',
      surface: '#18181B',
      text: '#FEF08A',
      mutedText: '#EAB308',
      accent: '#EAB308',
      accentSecondary: '#FACC15',
      glow: '0 0 30px rgba(234, 179, 8, 0.5)',
      card: 'rgba(24, 24, 27, 0.8)',
      border: 'rgba(234, 179, 8, 0.4)',
      gradient: 'from-zinc-950 via-neutral-900 to-stone-950',
    },
    particles: { type: 'fireflies', primaryColor: '#FACC15', secondaryColor: '#FEF08A', density: 35 },
    cursor: { glowColor: '#EAB308', trailEmoji: '⭐' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'grand_orchestral' },
    texture: 'aurora',
  },
  nature: {
    id: 'nature',
    name: 'Serene Nature & Mint',
    tagline: 'Floating autumn leaves, soft rainfall, and forest calm.',
    colors: {
      background: '#022C22',
      surface: '#064E3B',
      text: '#ECFDF5',
      mutedText: '#34D399',
      accent: '#10B981',
      accentSecondary: '#A7F3D0',
      glow: '0 0 25px rgba(16, 185, 129, 0.4)',
      card: 'rgba(6, 78, 59, 0.5)',
      border: 'rgba(52, 211, 153, 0.3)',
      gradient: 'from-emerald-950 via-teal-900 to-slate-950',
    },
    particles: { type: 'leaves', primaryColor: '#34D399', secondaryColor: '#A7F3D0', density: 30 },
    cursor: { glowColor: '#34D399', trailEmoji: '🍃' },
    typography: { headingFont: 'Satoshi', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'forest_birds' },
    texture: 'grain',
  },
  flowers: {
    id: 'flowers',
    name: 'Botanical Bloom',
    tagline: 'Lush lavender, peach petals, and floral elegance.',
    colors: {
      background: '#FAF5FF',
      surface: '#F3E8FF',
      text: '#581C87',
      mutedText: '#9333EA',
      accent: '#A855F7',
      accentSecondary: '#C084FC',
      glow: '0 0 20px rgba(168, 85, 247, 0.4)',
      card: 'rgba(255, 255, 255, 0.85)',
      border: 'rgba(192, 132, 252, 0.35)',
      gradient: 'from-purple-100 via-rose-100 to-peach-100',
    },
    particles: { type: 'sakura', primaryColor: '#C084FC', secondaryColor: '#F472B6', density: 35 },
    cursor: { glowColor: '#C084FC', trailEmoji: '🌺' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Sacramento' },
    audio: { ambientPreset: 'harp_breeze' },
    texture: 'cloud',
  },
  retro: {
    id: 'retro',
    name: 'Vintage Scrapbook',
    tagline: 'Sepia paper grain, faded polaroids, and nostalgic stamps.',
    colors: {
      background: '#FFFBEB',
      surface: '#FEF3C7',
      text: '#451A03',
      mutedText: '#B45309',
      accent: '#D97706',
      accentSecondary: '#F59E0B',
      glow: '0 0 15px rgba(217, 119, 6, 0.3)',
      card: 'rgba(254, 243, 199, 0.9)',
      border: 'rgba(180, 83, 9, 0.4)',
      gradient: 'from-stone-200 via-amber-100 to-yellow-100',
    },
    particles: { type: 'confetti', primaryColor: '#D97706', secondaryColor: '#B45309', density: 25 },
    cursor: { glowColor: '#D97706', trailEmoji: '📜' },
    typography: { headingFont: 'General Sans', handwritingFont: 'Caveat' },
    audio: { ambientPreset: 'vinyl_crackle' },
    texture: 'paper',
  },
  neon: {
    id: 'neon',
    name: 'Cyber Neon Night',
    tagline: 'Electric cyan, magenta glow, and futuristic pulse.',
    colors: {
      background: '#030712',
      surface: '#0F172A',
      text: '#67E8F9',
      mutedText: '#F43F5E',
      accent: '#06B6D4',
      accentSecondary: '#F43F5E',
      glow: '0 0 35px rgba(6, 182, 212, 0.6)',
      card: 'rgba(15, 23, 42, 0.8)',
      border: 'rgba(6, 182, 212, 0.5)',
      gradient: 'from-gray-950 via-slate-900 to-blue-950',
    },
    particles: { type: 'fireflies', primaryColor: '#06B6D4', secondaryColor: '#F43F5E', density: 40 },
    cursor: { glowColor: '#06B6D4', trailEmoji: '⚡' },
    typography: { headingFont: 'Clash Display', handwritingFont: 'Satisfy' },
    audio: { ambientPreset: 'synthwave_pulse' },
    texture: 'toxic_glow',
  },
};
